### ISSUE TITLE
"--log / -l" displays the wrong info.

### ISSUE THREAD

**Issue by nerd190** [kazhala/dump-cli#3]
Hi! me again! once again thank you for this utility.

`--log` shows the wrong info if a file contains a colon `:`

**Examples**
My current directory:
```bash

~/test ❯ ls -A
1.txt

```
Alot of people append a filename with a time and/or date, traditionally when backing something up, I have a function called `bak`, it renames a file in this format `FileName_$(date +%X_%d-%m-%C)`, like so:
```bash

~/test ❯ bak 1.txt && ls -A
1.txt       1.txt_20:30:37_02-02-20

```
With "1.txt" everything works perfectly:
```bash

~/test ❯ dump 1.txt
renamed '1.txt' -> '/home/5c0tt1/.local/share/Trash/1.txt'

~/test ❯ dump -l
Name                            Location                                                                              
1.txt                   /home/5c0tt/test/1.txt

```

The problem is with the time/dated file:
```bash

~/test ❯ dump 1.txt_20:30:37_02-02-20
renamed '1.txt_20:30:37_02-02-20' -> '/home/5c0tt/.local/share/Trash/1.txt_20:30:37_02-02-20'

~/test ❯ dump -l
Name                            Location
1.txt                   /home/5c0tt/test/1.txt
1.txt_20                            30

```

As you can see, the colon splits it and its location is listed as "30" (which is actually the minutes in the files time).
Strangely (and thankfully), even though no directory exists named "30", it doesnt cause any errors when using `--undo` !!!
```bash

~/test ❯ dump -u && ls -A
renamed '/home/5c0tt1/.local/share/Trash/1.txt_20:30:37_02-02-20' -> '/home/5c0tt1/test/1.txt_20:30:37_02-02-20'
1.txt_20:30:37_02-02-20

```

So I had another look at the script and its the `log` function's use of `awk -F ":"` which uses a colon as a deliminator because you log entries in this format:
```bash
1.txt-1: /data/data/com.termux/files/home/test/1.txt
```
As colons are valid characters used in file names, I would log entries differently, using something that files do not contain often and use that as the deliminator for `awk`. Perhaps use empty double brackets (I have never seen a file with empty double brackets in).
- `(())`
- `[[]]`
- `{{}}`

That way you can change `awk -F ":"` to either:
- `awk -F "(())"`
- `awk -F "[[]]"`
- `awk -F "{{}}"`

If you like the way it is already (`file: location`) then you could simply change it to `file  ::  location` (I have never seen a file with "two spaces-two colons-two spaces"), then use `awk -F "  ::  "` instead.

Then `--log` will display everything correctly.
Hope that helps and thanks again!

**Comment by kazhala** [comment]
Hi @5c0tt-b0t,

Thanks for reporting and offering fixes. You are absolutely correct, using ":" was a terrible choice tbh now that to think about. I will put up a fix soon, there are some other areas such as `file_path="${file_line##*: }"` also require fix if the delimiter does change.

Personally, I like `::` over other options but I'll experiment a little to see which one works the best.

Cheers,
Kevin

**Comment by nerd190** [comment]
@kazhala no problem at all, I like this utility alot, your scripting is clean and you have already achieved so much! I'm more than happy to contribute,.
The only reason I have reported these small fixes rather than submitting pull requests is that for such small tasks, its better for the dev to ammend them.
As for the future though, I would like to help make this even better, personally I feel it only lacks 2 small features that are easy to implement, both related to portability/extensibility:
- Default directory should conform to freedesktop.org trash standards:
`$XDG_DATA_HOME/Trash`
(`$XDG_DATA_HOME` defaults to `$HOME/.local/share` so the default path is `$HOME/.local/share/Trash`)
The user can still use any directory they choose, but it should default to the above, they can just export a variable to set, for example: `DUMP_DIR=/whatever/they/want`, then everyone has a choice but by doing this you get extensibility, for example, editors and file managers, like `nnn` etc use this directory to trash files by default.
- Currently, this isnt safe to alias to `rm`.
It will fail, alot! this is because it doesnt contain the main options, until now, I have been using this amazing utility written in Go: [gomi](https://github.com/b4b4r07/gomi)
It is very simple, whilst it doesnt contain every --long-option, it does cover the main ones, this is how:
(gomi only has these commands!)
```bash
~ ❯ gomi --help
Usage:
  gomi [OPTIONS]

Application Options:
  -b, --restore           Restore deleted file
  -B, --restore-by-group  Restore deleted files based on
                                         one operation

Help Options:
       --version           Show version
  -h, --help              Show this help message
```
It avoids problems by including dummy options:
```bash
Dummy options:
  -i                      To make compatible with rm
                          command
  -r                      To make compatible with rm
                          command
  -f                      To make compatible with rm
                          command
  -d                      To make compatible with rm
                          command
  -v                      To make compatible with rm
                          command
```
Once these are covered, it would be very rare to see an error.
(you already have `-i` (interactive) covered perfectly with `fzf`!)
So its only, change default directory (one value!) and add some dummy options to cover the majority of `rm`'s uses.
Then its **PERFECT!**

**Comment by kazhala** [comment]
Hi @5c0tt-b0t,

I've made some changes to the code and now it uses `<:::>` as the deliminator. Kinda weird but shouldn't clash with file names... In other places, this deliminator is exchanged to either spaces or `->` for visual effect only. `[]` or `{}` doesn't work well with `awk` and `sed` as they belong part of the regex and will introduce unnecessary complexity.

Can you please give it a try to see if other functionality still works as expected.

My apologies if `dump-cli` doesn't seem stable enough as I haven't done nearly enough testing on `dump-cli` as I should. Ideally, I would like to start creating some unittest when I find some time for it.

Thank you for your suggestions and issues, they are greatly appreciated. Feel free to open pull request, I'm open to them.

Regarding for your 2 latest points:

## Trash location

I have nothing against changing the default trash location to the xdg standard, was not aware it has it. Thank you for pointing out.

## Alias to rm

I would love to be able to alias `dump` to `rm`. It didn't support at the start was due to `trash-cli` didn't support and I did not bother with the reasons.

### Error

What could be the potential error if you alias dump to rm? My confusion would be if we have dummy options, it still won't work right? Or will it affect some other software leveraging rm?

### Implementation

If we wanna cover all the options, does it require to cover situations where the arguments is chained together like this `rm -irv` or does it not matter. 

At the moment, the current implementation doesn't support chained arguments as it doesn't use `getopts`. The positive of current implementation is that it can supports verbose arguments like `--clean`. 

Have not tried to implement something that supports both, do you have any suggestions?

Lastly I just wanna say I'm really glad you find dump-cli useful, I was not expecting users haha, hence did not bother with unittest, release or auto completion. From now on, they will be part of my plan and I'll keep working on improving dump-cli.

Cheers,
Kevin

**Comment by nerd190** [comment]
Awesome :)
No problem, glad I can be of help.
(I agree with `:::` good choice!)

### getops (with an 's')
`getopts` is a stripped down version of `getopt` built-in to bash, its good for simple scripting/utils, but not advanced options, its useful as it loops through each option retaining its positioning `$1 $2 $3` so you know what to query, but it cant handle combined options:
- `-a`                  (short opt)
- `-bc`                (multi short opts)
- `-d=1`              (short opt = value)
- `-e2`                 (short opts like cut has: `cut -d: -f1- ; cut -d/ -f2`)
- `--long-opt`      (long opt)
- `--long-opt=3`  (long opt = value)
etc etc...

### getop (no 's')
*All Unix users* (Linux, Mac, BSD etc) also have `getop`, it comes as standard, its even older than `getops` is.
On Linux (Arch, Ubuntu, Debian etc) we have a newer and much more advanced version included as standard with `util-linux`, its capable of handling the above options that `getops` cant.
Its available for all Unix users (you already have it) but Mac & BSD have the ancient version,  not the new one, luckily its super easy to install:
- with [homebrew/brew](https://github.com/Homebrew/brew) using `brew install util-linux` (for Mac, BSD & Linux)
- with [macports.org](http://www.macports.org) using `sudo port install getopt` (Mac only)

I highly recommend this, most Mac/BSD users do, or atleast those that live in the shell like we do, I'd put a "requirements" at the bottom of the README, just saying "Uses the advanced getop(3) from util-linux, those on Mac & BSD can get the newer, improved version here: (the links I posted above)".

As for the dummy options, 99% of them will just call this command: `dump "$@"` which is safe as its not really deleting anything, its backing it up, but by having the dummy options there covered, no errors.
As `rm -i` is interactive, your use of `dump -i` with `fzf` will be perfect as it is.

The only **rare**, but still important issue I can see is if, say a backup script used `rm --one-file-system` to remove everything in `/media` apart from the contents of any external mounted drives, then `dump` would delete the content of the mounts too, whilst everything is safely backed-up, what if its a full 4 terrabyte SSD, restoring it would be a pain.
As its not meant to be an rm replacement, lets not, in fact `rt` (for **r**m-**t**rash) would be a nice alias (or even name) for this, imagine the workflow: `rm = remove` & `rt = trash` (`rt` is even quicker than `rm` to type, easy to remember and much quicker than using (trash-cli workflow): `rm = remove` & `trash = trash`.
With the above workflow `rm - rt`, lets not bother with aliasing `rm`, whilst its do-able theres a reason all these years theres no proper `rm` replacement everyone uses and I doubt we're about to achieve it, all these years later, safely, all using bash! (`gomi` for instance is written in Go, others in Rust) perhaps it should be thought as brother to `rm`, much like `pushd` & `popd`, `head` & `tail`, `if` & `fi`, `case` & `esac` etc etc. ???
athis way its:
1. Its 100% safe in all situations,
2. Dont have tons of scripting to do (do one thing and do it well, rather than implement tons of features, let it just handle backing up)
3. A very fast, rememberable workflow `rm - rt`.

So, after teaching about `getop(3)` looks like I dont want you to use it at all! lol.
But you should seriously install it asap for future use!!!

**Comment by kazhala** [comment]
Hi @5c0tt-b0t,

Thanks for the comprehensive explanation. Sorry, couldn't get back earlier.

After reading the first part, I was considering experimenting with `util-linux`. I'm aware of `coreutils` but haven't heard or tried `util-linux`. I've been kinda reluctant to install these as I personally like to keep the dependency short. 

With that being said, I will look into experimenting with the `getops` from `utils-linux` and some other combinations to see if I could improve the options a little, it does feel nice to chain options like `rm -rf` rather than `rm -r -f`.....

For the second part, I agree, making this as a brother of `rm` sounds like an excellent idea so that we don't run into weird situations and avoid any potential risks. Also can keep the focus on improving `dump` rather than worrying about compatibilities.

Thank you for all the input and explanation. Leaving your full comments really let me understand your thought process of this hahaha.

**Did you have any chance testing the --log and other functionalities, does it still function properly after the change?** I will close the issue after your confirmation.

Cheers,
Kevin

**Comment by nerd190** [comment]
Sounds great! yes everything works great, thank you! allow me to close the issue.
Speak to you soon!
